dwc_field_map = {
    "taxon_id": "taxonID",
    "name": "scientificName",
    "fullname": "scientificNameAuthorship",
    "cname": "vernacularName",
    "alternative_name_c": "alternativeVernacularName",
    "family": "family",
    "family_cname": "familyVernacularName",
    "family_c": "familyVernacularName",
    "pt_name": "higherClassification",
    "kingdom": "kingdom",
    "kingdom_c": "kingdomVernacularName",
    "phylum": "phylum",
    "phylum_c": "phylumVernacularName",
    "class_name": "class",
    "class_c": "classVernacularName",
    "order": "order",
    "order_c": "orderVernacularName",
    "genus": "genus",
    "genus_c": "genusVernacularName",
    "abundance": "individualCount",
    "source": "establishmentMeans",
    "iucn_category": "iucnRedListCategory",
    "redlist": "nationalRedListCategory",
    "cites": "CITES",
    "protected": "protectionStatus",
    "endemic": "endemic",
    "is_hybrid": "isHybrid",
    "nomenclature_name": "nomenclaturalCode",
    "is_terrestrial": "isTerrestrial",
    "is_freshwater": "isFreshwater",
    "is_brackish": "isBrackish",
    "is_marine": "isMarine",
    "alien_status_note": "establishmentRemarks",
    "occurrenceID": "occurrenceID",
    "eventDate": "eventDate",
    "modified": "modified",
}

def convert_to_dwc(obj: dict) -> dict:
    return {dwc_field_map.get(k, k): v for k, v in obj.items()}
