/**
 * ISO 3166-1 alpha-2 regions with English and Traditional-Chinese (zh-Hant)
 * display names, for the country picker in the region-pack screen.
 *
 * Generated from ICU (Node Intl.DisplayNames, zh-Hant + en) rather than typed
 * from memory, then the exceptionally-reserved codes (AC, CP, DG, EA, IC, TA…)
 * were dropped — they are not countries and GBIF's COUNTRY enum rejects them.
 * Static data on purpose: Hermes' Intl support cannot be relied on for
 * DisplayNames on both platforms.
 */
export type Country = { code: string; en: string; zh: string };

export const COUNTRIES: Country[] = [
  { code: "AD", en: "Andorra", zh: "安道爾" },
  { code: "AE", en: "United Arab Emirates", zh: "阿拉伯聯合大公國" },
  { code: "AF", en: "Afghanistan", zh: "阿富汗" },
  { code: "AG", en: "Antigua & Barbuda", zh: "安地卡及巴布達" },
  { code: "AI", en: "Anguilla", zh: "安奎拉" },
  { code: "AL", en: "Albania", zh: "阿爾巴尼亞" },
  { code: "AM", en: "Armenia", zh: "亞美尼亞" },
  { code: "AN", en: "Curaçao", zh: "庫拉索" },
  { code: "AO", en: "Angola", zh: "安哥拉" },
  { code: "AQ", en: "Antarctica", zh: "南極洲" },
  { code: "AR", en: "Argentina", zh: "阿根廷" },
  { code: "AS", en: "American Samoa", zh: "美屬薩摩亞" },
  { code: "AT", en: "Austria", zh: "奧地利" },
  { code: "AU", en: "Australia", zh: "澳洲" },
  { code: "AW", en: "Aruba", zh: "荷屬阿魯巴" },
  { code: "AX", en: "Åland Islands", zh: "奧蘭群島" },
  { code: "AZ", en: "Azerbaijan", zh: "亞塞拜然" },
  { code: "BA", en: "Bosnia & Herzegovina", zh: "波士尼亞與赫塞哥維納" },
  { code: "BB", en: "Barbados", zh: "巴貝多" },
  { code: "BD", en: "Bangladesh", zh: "孟加拉" },
  { code: "BE", en: "Belgium", zh: "比利時" },
  { code: "BF", en: "Burkina Faso", zh: "布吉納法索" },
  { code: "BG", en: "Bulgaria", zh: "保加利亞" },
  { code: "BH", en: "Bahrain", zh: "巴林" },
  { code: "BI", en: "Burundi", zh: "蒲隆地" },
  { code: "BJ", en: "Benin", zh: "貝南" },
  { code: "BL", en: "St. Barthélemy", zh: "聖巴瑟米" },
  { code: "BM", en: "Bermuda", zh: "百慕達" },
  { code: "BN", en: "Brunei", zh: "汶萊" },
  { code: "BO", en: "Bolivia", zh: "玻利維亞" },
  { code: "BQ", en: "Caribbean Netherlands", zh: "荷蘭加勒比區" },
  { code: "BR", en: "Brazil", zh: "巴西" },
  { code: "BS", en: "Bahamas", zh: "巴哈馬" },
  { code: "BT", en: "Bhutan", zh: "不丹" },
  { code: "BU", en: "Myanmar (Burma)", zh: "緬甸" },
  { code: "BV", en: "Bouvet Island", zh: "布威島" },
  { code: "BW", en: "Botswana", zh: "波札那" },
  { code: "BY", en: "Belarus", zh: "白俄羅斯" },
  { code: "BZ", en: "Belize", zh: "貝里斯" },
  { code: "CA", en: "Canada", zh: "加拿大" },
  { code: "CC", en: "Cocos (Keeling) Islands", zh: "科克斯（基靈）群島" },
  { code: "CD", en: "Congo - Kinshasa", zh: "剛果（金夏沙）" },
  { code: "CF", en: "Central African Republic", zh: "中非共和國" },
  { code: "CG", en: "Congo - Brazzaville", zh: "剛果（布拉薩）" },
  { code: "CH", en: "Switzerland", zh: "瑞士" },
  { code: "CI", en: "Côte d’Ivoire", zh: "象牙海岸" },
  { code: "CK", en: "Cook Islands", zh: "庫克群島" },
  { code: "CL", en: "Chile", zh: "智利" },
  { code: "CM", en: "Cameroon", zh: "喀麥隆" },
  { code: "CN", en: "China", zh: "中國" },
  { code: "CO", en: "Colombia", zh: "哥倫比亞" },
  { code: "CR", en: "Costa Rica", zh: "哥斯大黎加" },
  { code: "CS", en: "Serbia", zh: "塞爾維亞" },
  { code: "CU", en: "Cuba", zh: "古巴" },
  { code: "CV", en: "Cape Verde", zh: "維德角" },
  { code: "CW", en: "Curaçao", zh: "庫拉索" },
  { code: "CX", en: "Christmas Island", zh: "聖誕島" },
  { code: "CY", en: "Cyprus", zh: "賽普勒斯" },
  { code: "CZ", en: "Czechia", zh: "捷克" },
  { code: "DD", en: "Germany", zh: "德國" },
  { code: "DE", en: "Germany", zh: "德國" },
  { code: "DJ", en: "Djibouti", zh: "吉布地" },
  { code: "DK", en: "Denmark", zh: "丹麥" },
  { code: "DM", en: "Dominica", zh: "多米尼克" },
  { code: "DO", en: "Dominican Republic", zh: "多明尼加共和國" },
  { code: "DY", en: "Benin", zh: "貝南" },
  { code: "DZ", en: "Algeria", zh: "阿爾及利亞" },
  { code: "EC", en: "Ecuador", zh: "厄瓜多" },
  { code: "EE", en: "Estonia", zh: "愛沙尼亞" },
  { code: "EG", en: "Egypt", zh: "埃及" },
  { code: "EH", en: "Western Sahara", zh: "西撒哈拉" },
  { code: "ER", en: "Eritrea", zh: "厄利垂亞" },
  { code: "ES", en: "Spain", zh: "西班牙" },
  { code: "ET", en: "Ethiopia", zh: "衣索比亞" },
  { code: "FI", en: "Finland", zh: "芬蘭" },
  { code: "FJ", en: "Fiji", zh: "斐濟" },
  { code: "FK", en: "Falkland Islands", zh: "福克蘭群島" },
  { code: "FM", en: "Micronesia", zh: "密克羅尼西亞" },
  { code: "FO", en: "Faroe Islands", zh: "法羅群島" },
  { code: "FR", en: "France", zh: "法國" },
  { code: "FX", en: "France", zh: "法國" },
  { code: "GA", en: "Gabon", zh: "加彭" },
  { code: "GB", en: "United Kingdom", zh: "英國" },
  { code: "GD", en: "Grenada", zh: "格瑞那達" },
  { code: "GE", en: "Georgia", zh: "喬治亞" },
  { code: "GF", en: "French Guiana", zh: "法屬圭亞那" },
  { code: "GG", en: "Guernsey", zh: "根息" },
  { code: "GH", en: "Ghana", zh: "迦納" },
  { code: "GI", en: "Gibraltar", zh: "直布羅陀" },
  { code: "GL", en: "Greenland", zh: "格陵蘭" },
  { code: "GM", en: "Gambia", zh: "甘比亞" },
  { code: "GN", en: "Guinea", zh: "幾內亞" },
  { code: "GP", en: "Guadeloupe", zh: "瓜地洛普" },
  { code: "GQ", en: "Equatorial Guinea", zh: "赤道幾內亞" },
  { code: "GR", en: "Greece", zh: "希臘" },
  { code: "GS", en: "South Georgia & South Sandwich Islands", zh: "南喬治亞與南三明治群島" },
  { code: "GT", en: "Guatemala", zh: "瓜地馬拉" },
  { code: "GU", en: "Guam", zh: "關島" },
  { code: "GW", en: "Guinea-Bissau", zh: "幾內亞比索" },
  { code: "GY", en: "Guyana", zh: "蓋亞那" },
  { code: "HK", en: "Hong Kong SAR China", zh: "中國香港特別行政區" },
  { code: "HM", en: "Heard & McDonald Islands", zh: "赫德島及麥唐納群島" },
  { code: "HN", en: "Honduras", zh: "宏都拉斯" },
  { code: "HR", en: "Croatia", zh: "克羅埃西亞" },
  { code: "HT", en: "Haiti", zh: "海地" },
  { code: "HU", en: "Hungary", zh: "匈牙利" },
  { code: "HV", en: "Burkina Faso", zh: "布吉納法索" },
  { code: "ID", en: "Indonesia", zh: "印尼" },
  { code: "IE", en: "Ireland", zh: "愛爾蘭" },
  { code: "IL", en: "Israel", zh: "以色列" },
  { code: "IM", en: "Isle of Man", zh: "曼島" },
  { code: "IN", en: "India", zh: "印度" },
  { code: "IO", en: "British Indian Ocean Territory", zh: "英屬印度洋領地" },
  { code: "IQ", en: "Iraq", zh: "伊拉克" },
  { code: "IR", en: "Iran", zh: "伊朗" },
  { code: "IS", en: "Iceland", zh: "冰島" },
  { code: "IT", en: "Italy", zh: "義大利" },
  { code: "JE", en: "Jersey", zh: "澤西島" },
  { code: "JM", en: "Jamaica", zh: "牙買加" },
  { code: "JO", en: "Jordan", zh: "約旦" },
  { code: "JP", en: "Japan", zh: "日本" },
  { code: "KE", en: "Kenya", zh: "肯亞" },
  { code: "KG", en: "Kyrgyzstan", zh: "吉爾吉斯" },
  { code: "KH", en: "Cambodia", zh: "柬埔寨" },
  { code: "KI", en: "Kiribati", zh: "吉里巴斯" },
  { code: "KM", en: "Comoros", zh: "葛摩" },
  { code: "KN", en: "St. Kitts & Nevis", zh: "聖克里斯多福及尼維斯" },
  { code: "KP", en: "North Korea", zh: "北韓" },
  { code: "KR", en: "South Korea", zh: "南韓" },
  { code: "KW", en: "Kuwait", zh: "科威特" },
  { code: "KY", en: "Cayman Islands", zh: "開曼群島" },
  { code: "KZ", en: "Kazakhstan", zh: "哈薩克" },
  { code: "LA", en: "Laos", zh: "寮國" },
  { code: "LB", en: "Lebanon", zh: "黎巴嫩" },
  { code: "LC", en: "St. Lucia", zh: "聖露西亞" },
  { code: "LI", en: "Liechtenstein", zh: "列支敦斯登" },
  { code: "LK", en: "Sri Lanka", zh: "斯里蘭卡" },
  { code: "LR", en: "Liberia", zh: "賴比瑞亞" },
  { code: "LS", en: "Lesotho", zh: "賴索托" },
  { code: "LT", en: "Lithuania", zh: "立陶宛" },
  { code: "LU", en: "Luxembourg", zh: "盧森堡" },
  { code: "LV", en: "Latvia", zh: "拉脫維亞" },
  { code: "LY", en: "Libya", zh: "利比亞" },
  { code: "MA", en: "Morocco", zh: "摩洛哥" },
  { code: "MC", en: "Monaco", zh: "摩納哥" },
  { code: "MD", en: "Moldova", zh: "摩爾多瓦" },
  { code: "ME", en: "Montenegro", zh: "蒙特內哥羅" },
  { code: "MF", en: "St. Martin", zh: "法屬聖馬丁" },
  { code: "MG", en: "Madagascar", zh: "馬達加斯加" },
  { code: "MH", en: "Marshall Islands", zh: "馬紹爾群島" },
  { code: "MK", en: "North Macedonia", zh: "北馬其頓" },
  { code: "ML", en: "Mali", zh: "馬利" },
  { code: "MM", en: "Myanmar (Burma)", zh: "緬甸" },
  { code: "MN", en: "Mongolia", zh: "蒙古" },
  { code: "MO", en: "Macao SAR China", zh: "中國澳門特別行政區" },
  { code: "MP", en: "Northern Mariana Islands", zh: "北馬利安納群島" },
  { code: "MQ", en: "Martinique", zh: "馬丁尼克" },
  { code: "MR", en: "Mauritania", zh: "茅利塔尼亞" },
  { code: "MS", en: "Montserrat", zh: "蒙哲臘" },
  { code: "MT", en: "Malta", zh: "馬爾他" },
  { code: "MU", en: "Mauritius", zh: "模里西斯" },
  { code: "MV", en: "Maldives", zh: "馬爾地夫" },
  { code: "MW", en: "Malawi", zh: "馬拉威" },
  { code: "MX", en: "Mexico", zh: "墨西哥" },
  { code: "MY", en: "Malaysia", zh: "馬來西亞" },
  { code: "MZ", en: "Mozambique", zh: "莫三比克" },
  { code: "NA", en: "Namibia", zh: "納米比亞" },
  { code: "NC", en: "New Caledonia", zh: "新喀里多尼亞" },
  { code: "NE", en: "Niger", zh: "尼日" },
  { code: "NF", en: "Norfolk Island", zh: "諾福克島" },
  { code: "NG", en: "Nigeria", zh: "奈及利亞" },
  { code: "NH", en: "Vanuatu", zh: "萬那杜" },
  { code: "NI", en: "Nicaragua", zh: "尼加拉瓜" },
  { code: "NL", en: "Netherlands", zh: "荷蘭" },
  { code: "NO", en: "Norway", zh: "挪威" },
  { code: "NP", en: "Nepal", zh: "尼泊爾" },
  { code: "NR", en: "Nauru", zh: "諾魯" },
  { code: "NU", en: "Niue", zh: "紐埃島" },
  { code: "NZ", en: "New Zealand", zh: "紐西蘭" },
  { code: "OM", en: "Oman", zh: "阿曼" },
  { code: "PA", en: "Panama", zh: "巴拿馬" },
  { code: "PE", en: "Peru", zh: "秘魯" },
  { code: "PF", en: "French Polynesia", zh: "法屬玻里尼西亞" },
  { code: "PG", en: "Papua New Guinea", zh: "巴布亞紐幾內亞" },
  { code: "PH", en: "Philippines", zh: "菲律賓" },
  { code: "PK", en: "Pakistan", zh: "巴基斯坦" },
  { code: "PL", en: "Poland", zh: "波蘭" },
  { code: "PM", en: "St. Pierre & Miquelon", zh: "聖皮埃與密克隆群島" },
  { code: "PN", en: "Pitcairn Islands", zh: "皮特肯群島" },
  { code: "PR", en: "Puerto Rico", zh: "波多黎各" },
  { code: "PS", en: "Palestinian Territories", zh: "巴勒斯坦自治區" },
  { code: "PT", en: "Portugal", zh: "葡萄牙" },
  { code: "PW", en: "Palau", zh: "帛琉" },
  { code: "PY", en: "Paraguay", zh: "巴拉圭" },
  { code: "QA", en: "Qatar", zh: "卡達" },
  { code: "RE", en: "Réunion", zh: "留尼旺" },
  { code: "RH", en: "Zimbabwe", zh: "辛巴威" },
  { code: "RO", en: "Romania", zh: "羅馬尼亞" },
  { code: "RS", en: "Serbia", zh: "塞爾維亞" },
  { code: "RU", en: "Russia", zh: "俄羅斯" },
  { code: "RW", en: "Rwanda", zh: "盧安達" },
  { code: "SA", en: "Saudi Arabia", zh: "沙烏地阿拉伯" },
  { code: "SB", en: "Solomon Islands", zh: "索羅門群島" },
  { code: "SC", en: "Seychelles", zh: "塞席爾" },
  { code: "SD", en: "Sudan", zh: "蘇丹" },
  { code: "SE", en: "Sweden", zh: "瑞典" },
  { code: "SG", en: "Singapore", zh: "新加坡" },
  { code: "SH", en: "St. Helena", zh: "聖赫勒拿島" },
  { code: "SI", en: "Slovenia", zh: "斯洛維尼亞" },
  { code: "SJ", en: "Svalbard & Jan Mayen", zh: "挪威屬斯瓦巴及尖棉" },
  { code: "SK", en: "Slovakia", zh: "斯洛伐克" },
  { code: "SL", en: "Sierra Leone", zh: "獅子山" },
  { code: "SM", en: "San Marino", zh: "聖馬利諾" },
  { code: "SN", en: "Senegal", zh: "塞內加爾" },
  { code: "SO", en: "Somalia", zh: "索馬利亞" },
  { code: "SR", en: "Suriname", zh: "蘇利南" },
  { code: "SS", en: "South Sudan", zh: "南蘇丹" },
  { code: "ST", en: "São Tomé & Príncipe", zh: "聖多美普林西比" },
  { code: "SU", en: "Russia", zh: "俄羅斯" },
  { code: "SV", en: "El Salvador", zh: "薩爾瓦多" },
  { code: "SX", en: "Sint Maarten", zh: "荷屬聖馬丁" },
  { code: "SY", en: "Syria", zh: "敘利亞" },
  { code: "SZ", en: "Eswatini", zh: "史瓦帝尼" },
  { code: "TC", en: "Turks & Caicos Islands", zh: "土克斯及開科斯群島" },
  { code: "TD", en: "Chad", zh: "查德" },
  { code: "TF", en: "French Southern Territories", zh: "法屬南部屬地" },
  { code: "TG", en: "Togo", zh: "多哥" },
  { code: "TH", en: "Thailand", zh: "泰國" },
  { code: "TJ", en: "Tajikistan", zh: "塔吉克" },
  { code: "TK", en: "Tokelau", zh: "托克勞群島" },
  { code: "TL", en: "Timor-Leste", zh: "東帝汶" },
  { code: "TM", en: "Turkmenistan", zh: "土庫曼" },
  { code: "TN", en: "Tunisia", zh: "突尼西亞" },
  { code: "TO", en: "Tonga", zh: "東加" },
  { code: "TP", en: "Timor-Leste", zh: "東帝汶" },
  { code: "TR", en: "Türkiye", zh: "土耳其" },
  { code: "TT", en: "Trinidad & Tobago", zh: "千里達及托巴哥" },
  { code: "TV", en: "Tuvalu", zh: "吐瓦魯" },
  { code: "TW", en: "Taiwan", zh: "台灣" },
  { code: "TZ", en: "Tanzania", zh: "坦尚尼亞" },
  { code: "UA", en: "Ukraine", zh: "烏克蘭" },
  { code: "UG", en: "Uganda", zh: "烏干達" },
  { code: "UK", en: "United Kingdom", zh: "英國" },
  { code: "UM", en: "U.S. Outlying Islands", zh: "美國本土外小島嶼" },
  { code: "US", en: "United States", zh: "美國" },
  { code: "UY", en: "Uruguay", zh: "烏拉圭" },
  { code: "UZ", en: "Uzbekistan", zh: "烏茲別克" },
  { code: "VA", en: "Vatican City", zh: "梵蒂岡" },
  { code: "VC", en: "St. Vincent & Grenadines", zh: "聖文森及格瑞那丁" },
  { code: "VD", en: "Vietnam", zh: "越南" },
  { code: "VE", en: "Venezuela", zh: "委內瑞拉" },
  { code: "VG", en: "British Virgin Islands", zh: "英屬維京群島" },
  { code: "VI", en: "U.S. Virgin Islands", zh: "美屬維京群島" },
  { code: "VN", en: "Vietnam", zh: "越南" },
  { code: "VU", en: "Vanuatu", zh: "萬那杜" },
  { code: "WF", en: "Wallis & Futuna", zh: "瓦利斯群島和富圖那群島" },
  { code: "WS", en: "Samoa", zh: "薩摩亞" },
  { code: "XK", en: "Kosovo", zh: "科索沃" },
  { code: "YD", en: "Yemen", zh: "葉門" },
  { code: "YE", en: "Yemen", zh: "葉門" },
  { code: "YT", en: "Mayotte", zh: "馬約特島" },
  { code: "YU", en: "Serbia", zh: "塞爾維亞" },
  { code: "ZA", en: "South Africa", zh: "南非" },
  { code: "ZM", en: "Zambia", zh: "尚比亞" },
  { code: "ZR", en: "Congo - Kinshasa", zh: "剛果（金夏沙）" },
  { code: "ZW", en: "Zimbabwe", zh: "辛巴威" },
];

/** Display name in the app's current language. */
export function countryName(code: string, lang: string): string {
  const c = COUNTRIES.find((x) => x.code === code);
  if (!c) return code;
  return lang.startsWith('zh') ? c.zh : c.en;
}
